kind: Secret
apiVersion: v1
metadata:
  name: attestation-collector-certs
  namespace: trustee-operator-system
type: Opaque
stringData:
  ca.crt: |
    TODO: insert your secret
  client.crt: |
    TODO: insert your secret
  client.key: |
    TODO: insert your secret
