kind: Secret
apiVersion: v1
metadata:
  name: sidecar-tls-deid-roberta
  namespace: trustee-operator-system
type: Opaque
stringData:
  server-cert: |
    TODO: insert your secret
  server-key: |
    TODO: insert your secret
