kind: Secret
apiVersion: v1
metadata:
  name: trustee-image-policy
  namespace: trustee-operator-system
type: Opaque
stringData:
  policy: |
    {
      "default": [
          {
          "type": "reject"
          }
      ],
      "transports": {
          "docker": {
              "quay.io/confidential-devhub/hospital-janine-app":
              [
                  {
                      "type": "sigstoreSigned",
                      "keyPath": "kbs:///default/cosign-key/pub"
                  }
              ],
              "quay.io/confidential-devhub/coco-secure-access-sidecar":
              [
                  {
                      "type": "sigstoreSigned",
                      "keyPath": "kbs:///default/cosign-key/pub"
                  }
              ],
              "quay.io/confidential-devhub/attestation-collector-sidecar-secure":
              [
                  {
                      "type": "sigstoreSigned",
                      "keyPath": "kbs:///default/cosign-key/pub"
                  }
              ]
          }
      }
    }
