kind: Secret
apiVersion: v1
metadata:
  name: cosign-key
  namespace: janine-dev
type: Opaque
stringData:
  pub: |
    -----BEGIN PUBLIC KEY-----
    MFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE8sAXiWHaNYhTHwdOgIXbIwa0MmGf
    +fUAT0jo7pTexF3kclcAb3tiA3kQyHvYr0XZc+c6gDV7uTdCCGQ9hr2rHQ==
    -----END PUBLIC KEY-----