---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: cvm-deployment-listener
  namespace: janine-dev
spec:
  to:
    kind: Service
    name: el-cvm-deployment-listener
  port:
    targetPort: http-listener
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
