apiVersion: v1
kind: Secret
metadata:
  name: hospital-demo-gitops-repo
  namespace: openshift-gitops
  labels:
    argocd.argoproj.io/secret-type: repository
type: Opaque
stringData:
  type: git
  url: https://github.com/rh-summit-coco/hospital-demo-gitops.git
  username: not-used
  password: "TODO: insert your secret"
