apiVersion: v1
kind: Secret
metadata:
  name: user-git-credential
  namespace: janine-dev
type: Opaque
stringData:
  # HTTPS Git clone in configure-vm and build-ansible-image (username + token/password)
  username: "TODO: insert your secret"
  password: "TODO: insert your secret"
