apiVersion: v1
kind: Secret
metadata:
  name: trustee-kbs
  namespace: janine-dev
type: Opaque
stringData:
  kbs-url: "https://TODO: insert your secret"
  kbs-cert.pem: |
    -----BEGIN CERTIFICATE-----
    TODO: insert your secret
    -----END CERTIFICATE-----
