apiVersion: v1
kind: Secret
metadata:
  name: aws-credentials-bigrock
  namespace: janine-dev
type: Opaque
stringData:
  # Mounted at /root/.aws/credentials in create-aws-vm (AWS CLI default profile)
  credentials: |
    [default]
    aws_access_key_id = TODO: insert your secret
    aws_secret_access_key = TODO: insert your secret
  config: |
    [default]
    region = us-east-2
