apiVersion: v1
kind: Secret
metadata:
  name: attestation-collector-certs-sealed
  namespace: janine-app
type: Opaque
stringData:
  ca.crt: |
    TODO: insert your secret
  client.crt: |
    TODO: insert your secret
  client.key: |
    TODO: insert your secret
---
apiVersion: v1
kind: Secret
metadata:
  name: azure-sealed
  namespace: janine-app
type: Opaque
stringData:
  connection-string: "TODO: insert your secret"
